print('My name is Jessica')
print("my name be sam")
print("I was born in ohio!!")
print("I was born in june")
print("my favorite food tonkotsu ramen")
print("I really love green tea")
print("I'm a Virgo")
